package Resource;

public  enum RequestCodes 
{
    LOGIN_DETAIL,
    STUDENT_REGISTER,
    FILTER_PAST_SESSION,
    FILTER_DATE,
    FILTER_SESSION,
    FILTER_SEARCH,
    LIVE_SESSION,
    INIT_UPCOMING_SESSION_MENTOR,
    INIT_UPCOMING_SESSION_STUDENT,
    SESSION_REGISTER,
    SESSION_ENROLL,
    QUERY_ASK,
    IS_SESSION_ACTIVE,
    STREAM,
    LOGOUT,
    TERMINATE
}
