package Resource;

public enum ResponseCodes 
{
    INIT_MENTOR_RESPONSE,
    INIT_STUDENT_RESPONSE,
    NEW_SESSION,
    SESSION_REGISTER_SUCCESS,
    SESSION_REGISTER_FAILED,
    FILTER_SUCCESS,
    LIVE_SESSION_INFO,
    LIVE_SESSION_HEADLINE,
    ADD_IN_FORM,
    INC_COUNT,
    NOT_ACTIVE,
    STREAM,
    CONFIRM_TERMINATE
}
